Move interface to the interfaces folder
GoodHive/app pull request #103
Opened 2023-06-06 13:19 UTC by LittleSweetGun

2023-06-06 13:20 UTC, LittleSweetGun commented
#100

2023-06-08 19:41 UTC, n1c01a5 requested changes

2023-06-08 19:41 UTC, n1c01a5 commented on app/companies/job-offer/job-offer-result.tsx
> +import JobOffer from "../../../interfaces/job-offer";
Use the helper `@interfaces` instead of `../../../`.

2023-06-08 19:42 UTC, n1c01a5 commented
@LittleSweetGun use @interfaces for all paths.

2023-06-12 05:36 UTC, merged