Feature/load data of my profile for talents (WIP)
GoodHive/app pull request #107
Opened 2023-06-21 13:44 UTC by LittleSweetGun

- Add wallet_address column in users table :
TABLE goodhive.users (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  job_headline VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  phone_country_code VARCHAR(10) NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  telegram VARCHAR(255),
  currency VARCHAR(100),
  rate VARCHAR(20),
  about_work TEXT NOT NULL,
  skills VARCHAR(255) NOT NULL,
  image_url VARCHAR (255),
  wallet_address VARCHAR (100) UNIQUE
);

- User has to reconnect to the wallet (or the wallet_address stay empty)
TODO : see why it's happening and how to resolve it

- Can't deploy for now because of error caused by @ts-ignore in auth/nonce and auth/verify

2023-06-21 14:42 UTC, LittleSweetGun commented
#67

2023-06-21 17:21 UTC, n1c01a5 requested changes

2023-06-21 17:21 UTC, n1c01a5 commented on app/layout.tsx
> +  const [walletAddress, setWalletAddress] = useState("");
Can you add the type maybe `string | null`.

2023-06-21 17:21 UTC, n1c01a5 commented on app/layout.tsx
> +        setAuthStatus("authenticated");
Why did you remove 

```
if (hasCookieNonce) {
          setAuthStatus("authenticated");
        } else {
          setAuthStatus("unauthenticated");
        }
        ```

2023-06-21 17:21 UTC, n1c01a5 commented on app/layout.tsx
> +        setWalletAddress(address);
We must set the address after the validation of the signature not before !

2023-06-28 14:47 UTC, n1c01a5 commented
@LittleSweetGun ok know we have to put the address to a react context to share it with the others component throw a hook.

2023-07-01 10:43 UTC, n1c01a5 requested changes

2023-07-01 10:43 UTC, n1c01a5 commented on app/layout.tsx
> +<html lang="en">
Bad indentation

2023-07-01 15:31 UTC, merged