adding Navbar component with links
GoodHive/app pull request #12
Opened 2022-12-22 20:49 UTC by alfonsom-cogent

I have added Navbar components and the suggested structure, just remember me if is necessary to migrate to TypeScript

2022-12-27 09:39 UTC, n1c01a5 requested changes

2022-12-27 09:39 UTC, n1c01a5 commented on components/ActiveLink.jsx
> +import Link from 'next/link'
For imports we will use double quotes.

2022-12-27 09:39 UTC, n1c01a5 commented on components/ActiveLink.jsx
> +import Link from 'next/link'
```
import { useRouter } from "next/router"
import Link from "next/link"
```

2022-12-27 09:39 UTC, n1c01a5 commented on components/ActiveLink.jsx
> +  const { asPath } = useRouter()
Add break line before any `return`

2022-12-27 09:39 UTC, n1c01a5 commented on components/ActiveLink.jsx
> +export const ActiveLink = ({ text, href }) => {
The component name is bad because it's a component link agnostic.

`LinkStyled` seems better.

2022-12-27 09:39 UTC, n1c01a5 commented on components/Navbar.jsx
> +import { ActiveLink } from './ActiveLink'
Use double quotes.

2022-12-27 09:39 UTC, n1c01a5 commented on pages/design/index.jsx
>  import Head from 'next/head'
Add break line between native and internal imports

2022-12-27 09:39 UTC, n1c01a5 commented on pages/index.tsx
> +// import styles from '../styles/Home.module.css'
Don't use module css and remove death code.

2022-12-27 09:39 UTC, n1c01a5 commented on pages/look-for-talent/index.jsx
> +// import styles from '../styles/Home.module.css'
Same

2022-12-27 09:39 UTC, n1c01a5 commented on pages/look-for-talent/index.jsx
> +import { Navbar } from '../../components/Navbar'
Same

2022-12-27 09:39 UTC, n1c01a5 commented on pages/look-for-talent/index.jsx
> +        <a
Use Link component.

2022-12-27 09:39 UTC, n1c01a5 commented
@alfonsom-cogent for name files we use `snake-case`.

2022-12-27 09:57 UTC, n1c01a5 commented
I have this error when I use navbar links :

```
next-dev.js?3515:20 Error: Abort fetching component for route: "/design"
    at handleCancelled (router.js?8684:502:27)
    at eval (router.js?8684:1437:17)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (_async_to_generator.js?0e30:13:1)
    at _next (_async_to_generator.js?0e30:31:1)
```

2022-12-27 09:59 UTC, n1c01a5 requested changes

2022-12-27 09:59 UTC, n1c01a5 commented on components/ActiveLink.jsx
> +      className={[asPath === href ? 'text-[#FFB805] underline' : '']}
Why do you use `[]` ?

2022-12-27 09:59 UTC, n1c01a5 commented on components/ActiveLink.jsx
> +      className={[asPath === href ? 'text-[#FFB805] underline' : '']}
Use double quotes for classnames params.

2022-12-30 04:12 UTC, alfonsom-cogent commented
I had troubles with husky in this branch, comment were fixed in $PR #14

2022-12-30 04:15 UTC, alfonsom-cogent commented
@n1c01a5 you can close this PR and remove this branch if needed

2023-01-04 01:07 UTC, closed without merging