adding typescript files
GoodHive/app pull request #14
Opened 2022-12-30 04:10 UTC by alfonsom-cogent

2023-01-03 16:41 UTC, n1c01a5 commented on components/Link_Styled.tsx
> +import { FC } from "react";
move to link-styled.tsx

2023-01-03 16:45 UTC, n1c01a5 requested changes

2023-01-03 16:45 UTC, n1c01a5 commented on pages/look-for-talent/index.tsx
> +import { Navbar } from "../../components/Navbar";
import { Navbar } from "../../components/navbar";

2023-01-03 16:45 UTC, n1c01a5 commented on pages/look-for-talent/index.tsx
> +export default function LookForTalent() {
LookingForTalent

2023-01-03 16:45 UTC, n1c01a5 commented on components/Link_Styled.tsx
> +    <Link className={className} href={href}>
add `rel`

2023-01-04 01:08 UTC, alfonsom-cogent commented on components/Link_Styled.tsx
> +import { FC } from "react";
done

2023-01-04 01:12 UTC, alfonsom-cogent commented on components/Navbar.tsx
> +import { LinkStyled } from "./Link_Styled";
done

2023-01-04 01:13 UTC, alfonsom-cogent commented on pages/look-for-talent/index.tsx
> +import { Navbar } from "../../components/Navbar";
done

2023-01-04 01:28 UTC, alfonsom-cogent commented on components/Navbar.tsx
> +import { LinkStyled } from "./Link_Styled";
I had to create a new component called nav-bar because the project was not able to refactor the navbar name

2023-01-04 01:28 UTC, alfonsom-cogent commented on pages/look-for-talent/index.tsx
> +import Head from "next/head";
done

2023-01-04 01:28 UTC, alfonsom-cogent commented on pages/look-for-talent/index.tsx
> +export default function LookForTalent() {
done

2023-01-04 16:15 UTC, n1c01a5 approved these changes

2023-01-04 16:15 UTC, merged