feat: company profile and create job feature completed
GoodHive/app pull request #145
Opened 2023-12-14 14:29 UTC by sabbirrifat

2024-01-22 15:27 UTC, n1c01a5 commented
Hi @sabbirrifat 👋 can you fix the deployment ?

2024-01-22 15:47 UTC, sabbirrifat commented
> Hi @sabbirrifat 👋 can you fix the deployment ?

hi @n1c01a5 , I think it is just showing because of some unresolved comments in vercel but deployment is working fine

2024-01-22 15:51 UTC, n1c01a5 requested changes
Looks good but can you fix some little issues :

- remove console logs
- use kebab-case for all filenames

2024-01-22 15:51 UTC, n1c01a5 commented on app/api/companies/create-job/route.ts
> +    console.log("jobId", jobId);
Can you remove logs

2024-01-22 15:51 UTC, n1c01a5 commented on app/api/companies/my-profile/route.ts
> +  console.log("wall address >>", walletAddress);
remove log

2024-01-22 15:51 UTC, n1c01a5 commented on app/api/companies/my-profile/route.ts
> +    console.log("company >>", company[0]);
remove log

2024-01-22 15:51 UTC, n1c01a5 commented on app/api/companies/update-escrow/route.ts
> +
```
    // Input Validation
    if (!id || typeof id !== 'number') { // Assuming 'id' is a numeric value
      return new Response(JSON.stringify({ message: "Invalid or missing job id" }), {
        status: 400,
      });
    }

    if (typeof escrowAmount !== 'number') { // Validate escrowAmount as a number
      return new Response(JSON.stringify({ message: "Invalid escrow amount" }), {
        status: 400,
      });
    }
```

2024-01-24 15:16 UTC, sabbirrifat commented on app/api/companies/create-job/route.ts
> +    console.log("jobId", jobId);
resolved!

2024-01-24 15:17 UTC, sabbirrifat commented on app/api/companies/my-profile/route.ts
> +  console.log("wall address >>", walletAddress);
resolved!

2024-01-24 15:17 UTC, sabbirrifat commented on app/api/companies/my-profile/route.ts
> +    console.log("company >>", company[0]);
resolved!

2024-01-24 15:19 UTC, sabbirrifat commented on app/companies/create-job/page.tsx
> +      console.log(error);
resolved!

2024-01-24 15:20 UTC, sabbirrifat commented on app/companies/my-profile/page.tsx
> +        console.log("profile >>", profileData);
resolved!

2024-01-24 15:20 UTC, sabbirrifat commented on app/constants/countriesData.js
> +export const countriesData =[
resolved!

2024-01-24 15:26 UTC, sabbirrifat commented on app/api/companies/update-escrow/route.ts
> +
resolved!

2024-01-24 15:28 UTC, sabbirrifat commented on app/companies/create-job/PopupModal/PopupModal.tsx
> +  const { jobId, open, onClose, type, onSubmit } = props;
@n1c01a5 Actually, I'm trying to follow a pattern to make components more readable. So even for the components that have fewer props still I'm doing it in this way. Lemme know what u think.

2024-01-27 01:19 UTC, merged