Fix/update picture route
GoodHive/app pull request #69
Opened 2023-05-09 13:28 UTC by LittleSweetGun

Update image_url in companies data base because of length issue:

CREATE TABLE goodhive.companies (
id SERIAL PRIMARY KEY,
headline VARCHAR(255) NOT NULL,
designation VARCHAR(100) NOT NULL,
address VARCHAR(100) NOT NULL,
country VARCHAR(100) NOT NULL,
city VARCHAR(100) NOT NULL,
phone_country_code VARCHAR(10) NOT NULL,
phone_number VARCHAR(20) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
telegram VARCHAR(255),
details TEXT NOT NULL,
image_url VARCHAR(255)
);

2023-05-09 13:43 UTC, LittleSweetGun commented
#52

2023-05-09 14:01 UTC, n1c01a5 requested changes

2023-05-09 14:01 UTC, n1c01a5 commented on app/companies/my-profile/page.tsx
> +      fetch("/api/picture", {
Use this format to be more consistant with the rest of the code :

```
const postImage = () = {
  try {
    // TODO
    const postImageResponse = fetch...
    
    setImageUrl(imageData.imageUrl))
    
  catch (e) {
    console.error(e)
  }
}

postImage()
```

2023-05-09 15:34 UTC, n1c01a5 requested changes

2023-05-10 12:10 UTC, LittleSweetGun commented
Upload of the image really slow with the new format of image fetch.

Temporary solution : User can't save the form until the image is uploaded (save button not enabled) . The URL won't be empty if the image is still uploading then.

2023-05-11 14:17 UTC, merged