Feature/style autosuggest input
GoodHive/app pull request #78
Opened 2023-05-12 12:31 UTC by LittleSweetGun

goodhive.job_offers table schema for now:

CREATE TABLE goodhive.job_offers (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    type_engagement VARCHAR(20) NOT NULL,
    description VARCHAR(255),
    duration VARCHAR(100) NOT NULL,
    rate_per_hour INT,
    budget VARCHAR(100),
    skills VARCHAR(255)
);

Will have to add a list of suggestions for type_engagement if we want it as an ENUM type.

2023-05-12 12:34 UTC, LittleSweetGun commented
#73

2023-05-12 15:50 UTC, n1c01a5 requested changes

2023-05-12 15:50 UTC, n1c01a5 commented on app/companies/create-job/page.tsx
>    const languages = [
Move this to global vars.

`NEXT_PUBLIC_SKILLS=Javascript,Solidity,SQL`

Rename to `skills`.

2023-05-12 15:50 UTC, n1c01a5 commented on app/companies/create-job/page.tsx
>        setValue("");
```
if (selectedSkills.includes(suggestion)) return setValue("");

setSelectedSkills([...selectedSkills, suggestion]);
```

2023-05-12 15:50 UTC, n1c01a5 commented on app/companies/create-job/page.tsx
> +        " rounded-full block me-5 w-full px-4 py-2 text-base font-normal text-gray-600 bg-clip-padding transition ease-in-out focus:text-black bg-gray-100 focus:outline-none focus:ring-0",
Remove useless ` `.

2023-05-15 12:49 UTC, LittleSweetGun commented
Add global var `skills` in .env:
NEXT_PUBLIC_SKILLS=JavaScript,Solidity,SQL,Tailwind,EtherJS,TypeScript,IPFS,ReactJS,NextJS

2023-05-15 15:48 UTC, n1c01a5 requested changes

2023-05-15 15:55 UTC, n1c01a5 commented
UX error:

- [ ] proposals of the select have the save background on the input so we cannot distinct both sections
- [ ] when we write something and enter it's remove the last item

@LittleSweetGun can you fix these bugs ?

2023-05-15 15:58 UTC, n1c01a5 requested changes

2023-05-15 15:58 UTC, n1c01a5 commented on app/companies/create-job/page.tsx
> +import { useRef, useState, FormEvent, ChangeEvent } from "react";
`useRef` is useless.

2023-05-15 15:58 UTC, n1c01a5 requested changes

2023-05-15 16:02 UTC, n1c01a5 requested changes

2023-05-15 16:02 UTC, n1c01a5 commented on app/companies/create-job/page.tsx
> +  const skills = process.env.NEXT_PUBLIC_SKILLS?.split(",") ?? [];
Move this to `constants/skills.js`

2023-05-16 13:11 UTC, n1c01a5 requested changes

2023-05-16 13:11 UTC, n1c01a5 commented on app/companies/create-job/page.tsx
>    const AutosuggestInput = () => {
Must `camelCase` name format, AutosuggestInput => autosuggestInput .

2023-05-16 17:10 UTC, merged