Feature/create page my profile experience (WIP)
GoodHive/app pull request #82
Opened 2023-05-16 07:58 UTC by LittleSweetGun

Route.ts is not working for now (can't upload the form)

CREATE TABLE goodhive.users_experience (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    type_employment VARCHAR(100),
    designation VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    contract_start VARCHAR(100) NOT NULL,
    contract_end VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    skills VARCHAR(255)
);

2023-05-16 08:31 UTC, n1c01a5 requested changes

2023-05-16 08:31 UTC, n1c01a5 commented on app/components/select-input.tsx
> +import { HiChevronDown } from "react-icons/hi";
Don't use a tierces library for this. It's overengineering.

2023-05-16 08:31 UTC, n1c01a5 commented on app/components/select-input.tsx
> +              onClick={() => handleSelect(option)}
onClick={(e) => setInputValue(e.target.value)}

2023-05-16 08:31 UTC, n1c01a5 commented on app/components/select-input.tsx
> +
```
useEffect(() => {
  if(//click somewhere)  setIsOptionsOpen(!isOptionsOpen),
 }, [window]
)
```

2023-05-16 08:31 UTC, n1c01a5 commented on app/design/page.tsx
>            ></Input>
/>

2023-05-16 08:31 UTC, n1c01a5 commented on app/talents/my-profile/experience/page.tsx
> +  const [value, setValue] = useState("");
Add types.

2023-05-16 08:31 UTC, n1c01a5 commented on app/talents/my-profile/experience/page.tsx
> +    )}`;
Use Date Object.

2023-05-16 08:31 UTC, n1c01a5 commented on app/talents/my-profile/experience/page.tsx
> +    { value: "2023", label: "2023" },
Generate it with loop.

2023-05-16 08:31 UTC, n1c01a5 commented on app/talents/my-profile/experience/page.tsx
> +          onSuggestionsClearRequested={onSuggestionsClearRequested}
setSuggestions([]);

2023-05-16 08:31 UTC, n1c01a5 commented on package.json
> +    "react-icons": "^4.8.0",
Don't import this

2023-05-19 15:33 UTC, n1c01a5 requested changes

2023-05-19 15:33 UTC, n1c01a5 commented on app/components/select-input.tsx
> +  console.log(inputValue);
Remove this log

2023-05-19 15:33 UTC, n1c01a5 commented on app/components/select-input.tsx
> +
Add comment to explain this component it's not working as expected

2023-05-19 15:33 UTC, n1c01a5 commented on app/constants/employmentType.js
> +export const employmentType = [
Use `snake-case` for the name file.

2023-05-19 15:33 UTC, n1c01a5 commented on app/talents/my-profile/experiences/page.tsx
> +  //const [selectedOption, setSelectedOption] = useState<string | null>(null);
Add comment to explain why this code is commented

2023-05-19 15:33 UTC, n1c01a5 commented on app/talents/my-profile/experiences/page.tsx
> +  const month: Option[] = Array.from({ length: 12 }, (_, index) => {
Can be simplify.

2023-05-19 15:33 UTC, n1c01a5 commented on app/talents/my-profile/experiences/page.tsx
> +  const endYear = parseInt(process.env.END_YEAR || "");
Default value must be integer not string.

2023-05-19 15:33 UTC, n1c01a5 commented on app/talents/my-profile/experiences/page.tsx
> +  const year = Array.from({ length: endYear - startYear + 1 }, (_, index) => {
Can be simplify.

2023-05-19 15:35 UTC, n1c01a5 requested changes

2023-05-19 15:35 UTC, n1c01a5 commented on app/talents/my-profile/experiences/page.tsx
> +      toast.success("Profile Saved!");
"Experience Saved!"

2023-05-22 15:43 UTC, n1c01a5 requested changes

2023-05-22 15:43 UTC, n1c01a5 commented on package.json
> +    "buffer": "^6.0.3",
Why this dep ?

2023-05-23 15:33 UTC, n1c01a5 approved these changes

2023-05-23 15:36 UTC, merged

2023-05-31 08:06 UTC, LittleSweetGun commented
#79 #74