(WIP)Feature/display talents from db
GoodHive/app pull request #85
Opened 2023-05-22 13:26 UTC by LittleSweetGun

TODO: Update talents-result so the cards will show the profils from the DB

Update goodhive.users table:
CREATE TABLE goodhive.users (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  job_headline VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  phone_country_code VARCHAR(10) NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  telegram VARCHAR(255),
  currency VARCHAR(100),
  rate VARCHAR(20),
  about_work TEXT NOT NULL,
  skills VARCHAR(255) NOT NULL,
  image_url VARCHAR (255)
);

2023-05-24 11:14 UTC, LittleSweetGun commented
TODO:
- Display talents image
- Redesign card and make it responsive

2023-05-24 12:25 UTC, n1c01a5 requested changes

2023-05-24 12:25 UTC, n1c01a5 commented on app/api/companies/search-talents/route.ts
> +      const data = await sql`SELECT * FROM goodhive.users`;
`users`

2023-05-24 12:25 UTC, n1c01a5 commented on app/api/companies/search-talents/route.ts
> +    // Return the fetched data as a response
Don't put obvious comment.

2023-05-24 12:25 UTC, n1c01a5 commented on app/companies/search-talents/page.tsx
>  import Header from "@/app/components/header";
Add break line between react and other imports.

2023-05-30 14:00 UTC, LittleSweetGun commented
Add currency in job_offers table

ALTER TABLE goodhive.job_offers
ADD currency VARCHAR(100)

2023-05-31 08:05 UTC, LittleSweetGun commented
#80 #84 #83

2023-06-04 15:07 UTC, merged