Feature/create page companies job offer
GoodHive/app pull request #93
Opened 2023-06-02 13:01 UTC by LittleSweetGun

No button to access the new page for now :
- have to choose whether to place it in talents or in companies

Missing the companies information because no connection between job_offer and companies tables

2023-06-02 15:10 UTC, LittleSweetGun commented
#92

2023-06-03 10:10 UTC, n1c01a5 commented
@LittleSweetGun for 

> Missing the companies information because no connection between job_offer and companies tables

It a one-to-many relation: `company -> job offers` .

To add this relation, we have to add a column `company_id` in the `job` table.

2023-06-03 10:37 UTC, n1c01a5 requested changes

2023-06-03 10:37 UTC, n1c01a5 commented on app/companies/job_offer/page.tsx
> +"use client";
Use snake-case and not underscore_case for the folder path.

2023-06-03 13:56 UTC, n1c01a5 approved these changes

2023-06-03 13:57 UTC, merged